<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYz0MNob\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYz0MNob/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYz0MNob.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYz0MNob\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYz0MNob\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yz0MNob',
    'container.build_id' => 'da937be5',
    'container.build_time' => 1644857111,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYz0MNob');
