api_platform:
    title: 'Symfony API'
    description: 'Notre API Symfony pour le Back-End'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
