<?php

namespace ContainerYz0MNob;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vp0t6gkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vp0t6gk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vp0t6gk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ActivityController::delete' => ['privates', '.service_locator.adIsG53', 'get_ServiceLocator_AdIsG53Service', true],
            'App\\Controller\\ActivityController::desinscription' => ['privates', '.service_locator.adIsG53', 'get_ServiceLocator_AdIsG53Service', true],
            'App\\Controller\\ActivityController::edit' => ['privates', '.service_locator.adIsG53', 'get_ServiceLocator_AdIsG53Service', true],
            'App\\Controller\\ActivityController::index' => ['privates', '.service_locator.U55iHjJ', 'get_ServiceLocator_U55iHjJService', true],
            'App\\Controller\\ActivityController::inscription' => ['privates', '.service_locator.adIsG53', 'get_ServiceLocator_AdIsG53Service', true],
            'App\\Controller\\ActivityController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ActivityController::show' => ['privates', '.service_locator.z3PlX1K', 'get_ServiceLocator_Z3PlX1KService', true],
            'App\\Controller\\ActivityController::showParticipants' => ['privates', '.service_locator.z3PlX1K', 'get_ServiceLocator_Z3PlX1KService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.TbRD.tI', 'get_ServiceLocator_TbRD_TIService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UserController::downgrade' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController::setAdmin' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController::setAnimator' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\ActivityController:delete' => ['privates', '.service_locator.adIsG53', 'get_ServiceLocator_AdIsG53Service', true],
            'App\\Controller\\ActivityController:desinscription' => ['privates', '.service_locator.adIsG53', 'get_ServiceLocator_AdIsG53Service', true],
            'App\\Controller\\ActivityController:edit' => ['privates', '.service_locator.adIsG53', 'get_ServiceLocator_AdIsG53Service', true],
            'App\\Controller\\ActivityController:index' => ['privates', '.service_locator.U55iHjJ', 'get_ServiceLocator_U55iHjJService', true],
            'App\\Controller\\ActivityController:inscription' => ['privates', '.service_locator.adIsG53', 'get_ServiceLocator_AdIsG53Service', true],
            'App\\Controller\\ActivityController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ActivityController:show' => ['privates', '.service_locator.z3PlX1K', 'get_ServiceLocator_Z3PlX1KService', true],
            'App\\Controller\\ActivityController:showParticipants' => ['privates', '.service_locator.z3PlX1K', 'get_ServiceLocator_Z3PlX1KService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.TbRD.tI', 'get_ServiceLocator_TbRD_TIService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UserController:downgrade' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController:setAdmin' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController:setAnimator' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\ActivityController::delete' => '?',
            'App\\Controller\\ActivityController::desinscription' => '?',
            'App\\Controller\\ActivityController::edit' => '?',
            'App\\Controller\\ActivityController::index' => '?',
            'App\\Controller\\ActivityController::inscription' => '?',
            'App\\Controller\\ActivityController::new' => '?',
            'App\\Controller\\ActivityController::show' => '?',
            'App\\Controller\\ActivityController::showParticipants' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::downgrade' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::setAdmin' => '?',
            'App\\Controller\\UserController::setAnimator' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ActivityController:delete' => '?',
            'App\\Controller\\ActivityController:desinscription' => '?',
            'App\\Controller\\ActivityController:edit' => '?',
            'App\\Controller\\ActivityController:index' => '?',
            'App\\Controller\\ActivityController:inscription' => '?',
            'App\\Controller\\ActivityController:new' => '?',
            'App\\Controller\\ActivityController:show' => '?',
            'App\\Controller\\ActivityController:showParticipants' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:downgrade' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:setAdmin' => '?',
            'App\\Controller\\UserController:setAnimator' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
